### ISSUE TITLE
[Bug] API Localization

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/navigatum#168]
**Describe the bug**
Currently, our API does not localize Strings.

**To Reproduce**
1. Request `https://nav.tum.sexy/api/get/mi`
2. See `props` like `Raumkennung`, `Adresse`, ...
3. See `type_common_name` like `Gebiet / Gruppe von Geb\u00e4uden`

**Expected behavior**
At at least partially localized result, to make things like https://github.com/TUM-Dev/Campus-Android/blob/a143a0cb268347bf6b8ea537083434a79754dcc2/app/src/main/java/de/tum/in/tumcampusapp/component/tumui/roomfinder/NavigationDetailsFragment.kt#L161 something that is not needed

**Comment by octycs** [comment]
This is something I also though about, but didn't have an idea that I liked so far. What I thought about:

- Should we export two differently localized versions of the data (two JSONs), or just one JSON that has both strings for each string. The first option appears more inefficient in terms of storage, but would be simpler to implement in the server (e.g. two tables in the database). A hybrid option could be to export one JSON, but the `load_api_data_to_db.py` scripts splits it into two tables.
- How should we handle localization search? Two different indices, or just one with strings in both languages. I think the search results should be independent of the language setting. So the second approach is probably better (one index, but searchable with keywords in different languages). We would need to try out how we can achieve this without too much performance decrease.
- Should we localize names? E.g. "Rudolf-Diesel-Hörsaal" into "Rudolf-Diesel lecture hall", or "Nordgelände" into "North Campus".

A first step could be the info tables (like in the PR you linked above), because this does not affect search.

**Comment by CommanderStorm** [comment]
I will get on this next week, once my exams are done
