### ISSUE TITLE
[Bug] Some rooms are missing in NavigaTUM

### ISSUE THREAD

**Issue by octycs** [TUM-Dev/NavigaTUM#177]
**Describe the bug**
Some rooms in NavigaTUM are missing, that do exist in TUMOnline. We should find out why.
Possible ideas:
- Scraping doesn't get all entries
- Scraping does get all entries, but they were not in TUMOnline for some reason at the time of scraping.

I verified that they were not just discarded in the data compilation step.

**To Reproduce**
Lookup e.g. in TUMOnline:
5510.EG.012A (0012A, Büro)
5510.EG.099T (Treppe Hof 0)
5505.EG.529B (0529B, Büro)
5506.EG.699V (0699V, Treppe)

All these rooms are not in NavigaTUM as was seen in #175.

**Expected behavior**
All rooms from TUMOnline should at least be somewhere in the data (even if hidden).

**Additional context**
There are a lot of rooms in the Roomfinder but not in TUMOnline.

**Comment by N0W0RK** [comment]
There are also Rooms that are completely missing from TUM Online like the rooms at the MRI Klinikum rechts der Isaar

**Comment by CommanderStorm** [comment]
> There are also Rooms that are completely missing from TUM Online like the rooms at the MRI Klinikum rechts der Isaar

nav.tum.sexy may be spotty there too.
Do you have an example room(code)?
Are you talking about one room/a class of rooms/a building, or arbitrary spottyness?

Optional:
Is said example findable in TUMOnline/the mytum Roomfinder/the physics Roomfinder?

As context:
We get data from tumonline+mytum, but are some cases where the data does not match (there are rooms in both which are not in the other.. sigh).
We have not tapped into the physics Roomfinder, since I was promised an API for that.

However, we can always just patch in rooms (like we did for some rooms and are going to do for Ottobrunn.)
If you give us which rooms(roomcode, name given from the architect, tum roomcode, roomname) and in which buildings they are in we can just add them.  
There are other optional fields (coordinates, Floor, building address, image) but they are not so relevant as the ones mentioned above.
For adding coordinates of rooms we know about we even have a coordinate picker at nav.tum.de
