### ISSUE TITLE
unintended 404s

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/navigatum#21]
- When clicking on the change-language-button on `/about/privacy` and similar sites, we get a 404 error.
- when force-reloading any website, that is not the root
- editing an website-url to be invalid for example `/building/mi`->`/building/mü`

I have not tested if this is related to the deployment or a client issue.

**Comment by octycs** [comment]
The 404 is an Nginx issue (and also happens when you're on an entry page and reload the page). I tried to fix it in the last commit, not sure whether it is automatically deployed. Basically all URLs that are not `js/css/...` should redirect to the index file (e.g. URLs such as `/building/mi`; See [vue-router documentation](https://router.vuejs.org/guide/essentials/history-mode.html#nginx)).

However the page linking itself is not yet implemented. All `/about/` pages are simply rendered markdown files without being linked to a language.

**Comment by CommanderStorm** [comment]
resolved by https://github.com/TUM-Dev/navigatum/commit/e7d2212e3f1c3959eb52dca8ca7a74fbf9f607f6

**Comment by CommanderStorm** [comment]
Weird. After gathering screenshots for another issue I noticed, that this is indeed not fixed, even though it seemed like it

**Comment by CommanderStorm** [comment]
Another weird thing is, that what theme is selected seems to have an partial impact on the results (ngnix 404 or vue 404)

**Comment by CommanderStorm** [comment]
resolved by [e5cf20bd414a70b47b4279d3a8a0379fb182bc36](https://github.com/TUM-Dev/navigatum/commit/05b794c91f9d2ef2e850024611a7eb2a33429063)
