### ISSUE TITLE
migrate webclient to Vue-3

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/NavigaTUM#33]
Currently the webclient works on vue-2.
Vue-3 is out, so we should look into adopting this.
The migration guide can be found here: https://v3.vuejs.org/guide/migration/introduction.html

**Comment by octycs** [comment]
I was a bit hesitant because of browser support. Currently navigatum has support with polyfills back to IE10 and especially also old Android browsers (back to Chrome 37 in Android 5), which some still use. But if we know that few enough people are affected by this, we could drop them.

(I think dropping IE is okay nowadays, but I am not sure about Android)
