### ISSUE TITLE
[Bug] (analoge/physical) Printing of the `details` webpage

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/NavigaTUM#420]
**Describe the bug**
Currently, printing our webpage means that the cross is not at the intended place

**To Reproduce**
Steps to reproduce the behaviour:

1. Print (Ctrl+P) our webpage
2. See deviated coordinates

**Expected behaviour**
The print view should be as good as our non-print view

**Screenshots**
Problem:
![image](https://user-images.githubusercontent.com/26258709/221835027-74ef715a-0845-4a79-baa2-67f988417dab.png)
![image](https://user-images.githubusercontent.com/26258709/221835147-f34da27a-292d-4449-aeb4-5169efd834b6.png)

Expected location:
![image](https://user-images.githubusercontent.com/26258709/221837882-cbf96022-e3c3-48db-80d8-e1cf1af45689.png)

**Desktop:**

- OS: ?
- Browser chrome, edge, firefox
- Version latest, latest, esr

**Additional context**
This issue was raised by a Professor on our mailinglist

**Comment by octycs** [comment]
The problem seems to be that the map image gets scaled down (at least in browser pixel units; it was less pixels width/height in the preview) when using the printing preview, so the computed cross position (set in pixels). I tried solving it using percentage values instead, but it seems this doesn't help (probably because the cross image is again not scaled).

Another solution could be to use [beforeprint](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeprint_event) and manually render it on a canvas in JS. Probably the most stable option and it would allow to create a "download map" function. (But it's not of high priority, as long as you can just screenshot)
