### ISSUE TITLE
[Feature] Python Type correctness in the `external`⇋`pipeline` Interface

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/NavigaTUM#496]
**Is your feature request related to a problem? Please describe.**
Currently our python typing is barely existing.

**Describe the solution you'd like**
I would like to have most of our interfaces between the external scrapers and the main code typed via a tool like https://docs.pydantic.dev/ 

**Describe alternatives you've considered**
Typing via dataclasses/attrs.
The main reason why I think that pydantic is the way to go is, that this way we will know if something breaks quicker.

**Additional context**
This is a discussion, because this could cause more coupling between components which currently are not coupled at all
@octycs what are your thoughts on this matter?

**Comment by octycs** [comment]
I agree given that external data should always be validated. It might also serve as some kind of documentation. My suggestion would be to put the classes in `data/external/schemas/` (preferred since it's closer to the scraper scripts) or `data/schemas/` (if we intend to use it for the main pipeline or parts of it as well in the future and don't want two schema directories)
