### ISSUE TITLE
[Feature] Enable google indexing

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/navigatum#91]
**Is your feature request related to a problem? Please describe.**
Google currently fails to parse our website.

**Describe the solution you'd like**
To remidy this, we should

- add a sitemap
      - [ ] the sitemap should look at the currently deployed site to figure out if the content was updated
      - [ ] for this to be effective, we should consider adding the image hashes to the api
      - [ ] It should include an index, that links to all pages generated by the webclient and the data urls in a different file.
       The max-sice of these maps has to be respected.
- [ ] add canonical urls 
- [ ] fix why google does not find our subsites

Preferably we should implement all three.
**Describe alternatives you've considered**
Just fixing issue bulletpoint 3 would probably be sufficient, but since google is currently prefering navigatum.tum.sexy instead of nav.tum.sexy at least 2 should be adressed as well.

**Additional context**
The issue google has could be because of a too strict robots.txt
Any disallowances before have been lifted in https://github.com/TUM-Dev/navigatum/commit/d4aea9541e6d8d4c1e54ce3d0a60c6bf4fd9a7db

**Comment by octycs** [comment]
[Since sitemaps can be hierarchical](https://www.sitemaps.org/protocol.html#sitemapIndexXMLExample), what do you think about this:
- on data compilation, several (they have to be <50MB) sitemaps and one sitemap-index is created for the entry pages
- on webclient compilation, one webclient sitemap with the about pages is generated
- the main sitemap itself is a static one that points to the data sitemap-index and webclient sitemap
