### ISSUE TITLE
Add Infro PR Checks?

### ISSUE THREAD

**Issue by colethienes** [TUM-Dev/NavigaTUM#999]
I noticed that this repo uses Argo CD, and I thought I’d let you know that I recently released a Github app called Infro that several companies use internally that allows Argo CD users to preview Kubernetes changes in Github pull requests before they merge. I’m providing it for free to open source projects ([here’s](https://github.com/broersma-forslund/homelab/pull/158#issuecomment-1962289857) an example in the wild). [Here’s](https://medium.com/@colethienes/argocd-pull-request-checks-c863190c5f8c?source=friends_link&sk=2eda79520de33483591448c6dfe8d284) a setup guide with links to documentation. It’s in early stages, so I’m sure there will be warts. All feedback is welcome!

**Comment by CommanderStorm** [comment]
Thanks for reaching out.

To be honest, we are planning to migrate away from kubernetes (towards docker-compose).
The added complexity (and security risks ^^) of having to run a distributed system for a static workload has not proven themselves.
Room searching for universities fluctuates a bit (people search in the exam phase and at the start of the semester), but not enough to ever exceed 10% CPU.
No second container has ever been necessary and since we run our cluster on fixed infrastructure (it takes about a month to get a new VM via our "cloud" provider)

=> closing as not planned

**Comment by colethienes** [comment]
Got it! Thanks for the context!
